### ISSUE TITLE
User Profile: Create UI to view profile

### ISSUE THREAD

**Issue by ShimizuKazuki** [matsuoharuki/pbl2_group2#10]
Goal: The user must be able to view user's profile.

Success: When account button is pushed, the user profile page is appeared.

[Points: 3]

[Value: Medium]

[Risk: Low]

Tasks

- [x] Create UI to view profile. (~ 1 時間)
- [x] Create Button to link edit page. (~ 1 時間)
- [x] Working with the backend. (~ 1時間)

**Comment by matsuoharuki** [comment]
![IMG_0613](https://user-images.githubusercontent.com/49428871/95715287-8de99f00-0ca4-11eb-8c2f-ca990f5fbfd4.jpg)
