### ISSUE TITLE
Develop improve

### ISSUE THREAD

**Issue by matsuoharuki** [matsuoharuki/pbl2_group2#113]
If you have any improvements you want to make to the develop branch, please comment here!

**Comment by matsuoharuki** [comment]
- [ ] Map have to set min zoom scale.
- [x] If this system cannot get spot info, we have to start exception handling.

**Comment by ShimizuKazuki** [comment]
- [] Spot pins should be colored in a different color for each category

**Comment by Asada0815** [comment]
Spot pin should have icons corresponding to each spot types.

**Comment by matsuoharuki** [comment]
> Spot pins should be colored in a different color for each category

If we realize it, we have to create spot icon design.

**Comment by Asada0815** [comment]
> If we realize it, we have to create spot icon design. 
 
I think it would be easy if there was a way to use google material design.
