### ISSUE TITLE
Map Functionalities: Create UI to show map 

### ISSUE THREAD

**Issue by ShimizuKazuki** [matsuoharuki/pbl2_group2#17]
Goal: The user must be able to view map.

Success: When user open this page, the map appear.

[Points: 5]

[Value: High]

[Risk: Low]

Tasks

- [x] Show the map.  (~ 1 時間)
- [x] Create spot register bottun (~ 1 時間)
- [x] Create spot-type icon(~ 3 時間)
 - account 
 - create spot

**Comment by matsuoharuki** [comment]
![IMG_0612](https://user-images.githubusercontent.com/49428871/95714933-f6844c00-0ca3-11eb-8c1b-41f26637c54d.jpg)

**Comment by matsuoharuki** [comment]
現在地アイコンは保留で
