### ISSUE TITLE
Spot Functionalities: View spot details

### ISSUE THREAD

**Issue by ShimizuKazuki** [matsuoharuki/pbl2_group2#19]
Goal: The user must be able to view spots.

Success: 

[Points: 13]

[Value: High]

[Risk: Low]

Tasks

- [x] Create template (~ 1 時間)
- [x] Create UI to view spot information (~ 3 時間)
- [x] Create UI to view spot review (~ 2 時間)
- [x] Create UI to view spot evaluation graph (~ 2 時間)
- [x] Link spot information to map (~ 1 時間)

**Comment by matsuoharuki** [comment]
![IMG_0611](https://user-images.githubusercontent.com/49428871/95709062-ce432000-0c98-11eb-9619-5ef8ddfd8f93.jpg)
