### ISSUE TITLE
Map Functionalities: Create map filtering function

### ISSUE THREAD

**Issue by ShimizuKazuki** [matsuoharuki/pbl2_group2#22]
Goal: We must be able to generate custom database requests based on filtering.

Success: The database is able to send back data based on filtering criterias.
                 Supported filtering criterias: name, type of spot, coordinates, average score

[Points: 3]

[Value: Medium]

[Risk: Low]

Tasks
- [x]  Create function to receive custom database queries from front-end (~1 時間)
- [x]  Create SQL queries containing filtering critera (~30分)

Types of filtering: 
Name (~0.5 時間)
Type (Restaurant,school,...) (~0.5 時間)
Average review score (~0.5 時間)

**Comment by matsuoharuki** [comment]
検索条件がうまくいってない
