### ISSUE TITLE
Rest-API: Create App Routes

### ISSUE THREAD

**Issue by ONourry** [matsuoharuki/pbl2_group2#27]
Goal: Create the routes using express js to transfer data between the app (front-end) and the server (back-end)

Success: We are able to call functions and transfer data between front-end and back-end

[Points 5]

Tasks:
 - [x] Create /profile route
- [x] Create /register route
- [x] Create /login route
- [x] Create /map route
- [x] Create details route

Add Logger

**Comment by ONourry** [comment]
![routes_setup](https://user-images.githubusercontent.com/11179982/95709194-20844100-0c99-11eb-8cce-bf738547402b.jpeg)

**Comment by ShimizuKazuki** [comment]
![image0](https://user-images.githubusercontent.com/49428312/95709904-9f2dae00-0c9a-11eb-841a-8ab3be7495f0.jpg)

**Comment by ShimizuKazuki** [comment]
![Uploading image1.jpg…]()

**Comment by ShimizuKazuki** [comment]
![image1](https://user-images.githubusercontent.com/49428312/95710006-cb492f00-0c9a-11eb-9382-ccfa5de865bc.jpg)
