### ISSUE TITLE
Refactoring Issue

### ISSUE THREAD

**Issue by ONourry** [matsuoharuki/pbl2_group2#98]
If you find anything that requires refactoring later on or warning in the web console that indicates we need to refactor, please write it down here. 後でリファクタリングが必要なものや、リファクタリングが必要であることを示す警告がウェブコンソールに表示されたら、ここに書き留めておいてください

- [x] warnings that the key should be number. (`front/src/components/SpotDetail/SpotReviewList.vue`)
- [x] Exception handling for getting current location(front/src/components/Map/Map.js)
- [x] "TypeError: Cannot read property 'name' of null" (front/src/components/UserProfile/UserProfile.vue)

**Comment by matsuoharuki** [comment]
もし今後マップオブジェクトとスポットオブジェクトを別のファイルに分けられるのなら、将来コンポーネントを分割したいです。
- [ ] devide map component into map functionality and spot functionality.
